VuelaWebApp/VuelaWebApp/Models/consultaGeneralVuelos_Result.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuelaWebApp.Models
{
    using System;
    
    public partial class consultaGeneralVuelos_Result
    {
        public int idlineavuelo { get; set; }
        public System.DateTime horapartida { get; set; }
        public System.DateTime horallegada { get; set; }
        public Nullable<decimal> cantescalas { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string paisOrigen { get; set; }
        public string paisDestino { get; set; }
    }
}

VuelaWebApp/VuelaWebApp/Controllers/consultaGeneralVuelos_ResultController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VuelaWebApp.Models;

namespace VuelaWebApp.Controllers
{
    public class consultaGeneralVuelos_ResultController : Controller
    {
        private Entities db = new Entities();

        // GET: consultaGeneralVuelos_Result
        public ActionResult VuelosLista()
        {
            return View(db.consultaGeneralVuelos().ToList());
        }


        public ActionResult VuelosFiltrados(string paisOrigen, string paisDestino)
        {
            return View(db.consultaFitradaVuelos(paisOrigen,paisDestino).ToList());

        }
        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VuelaWebApp/VuelaWebApp/Views/consultaGeneralVuelos_Result/VuelosFiltrados.cshtml
@model IEnumerable<VuelaWebApp.Models.consultaGeneralVuelos_Result>

@{
    ViewBag.Title = "VuelosFiltrados";
}

<h2>Vuelos Filtrados</h2>

@using (Html.BeginForm("VuelosFiltrados", "consultaGeneralVuelos_Result", FormMethod.Get))
{
    <div class="row">
        <div class="form-group col-md-6">
            <label for="paisOrigen">Pais Origen</label>
            <input type="text" class="form-control" id="paisOrigen" name="paisOrigen" placeholder="Pais Origen">
        </div>

        <div class="form-group col-md-6">
            <label for="paisDestino">Pais Destino</label>
            <input type="text" class="form-control" id="paisDestino" name="paisDestino" placeholder="Pais Destino">
        </div>

        <div class="form-group col-md-6">
            <label for="pConsultar">Filtrar</label>
            <input type="submit" value="Filtrar" class="btn btn-default" />
        </div>
    </div>
}


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.idlineavuelo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.paisOrigen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.paisDestino)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.horapartida)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.horallegada)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cantescalas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.precio)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.idlineavuelo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.paisOrigen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.paisDestino)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.horapartida)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.horallegada)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cantescalas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.precio)
            </td>
        </tr>
    }

</table>

VuelaWebApp/VuelaWebApp/Views/consultaGeneralVuelos_Result/VuelosLista.cshtml
@model IEnumerable<VuelaWebApp.Models.consultaGeneralVuelos_Result>

@{
    ViewBag.Title = "VuelosLista";
}

<h2>Vuelos Disponibles</h2>

@using (Html.BeginForm("VuelosFiltrados","consultaGeneralVuelos_Result",FormMethod.Get))
{
<div class="row">
<div class="form-group col-md-6">
    <label for="paisOrigen">Pais Origen</label>

    <input type="text" class="form-control" id="paisOrigen" name="paisOrigen" placeholder="Pais Origen">
</div>

<div class="form-group col-md-6">
    <label for="paisDestino">Pais Destino</label>
    <input type="text" class="form-control" id="paisDestino" name="paisDestino" placeholder="Pais Destino">
</div>

<div class="form-group col-md-6">
        <label for="pConsultar">Filtrar</label>
        <input type="submit" value="Filtrar" class="btn btn-default" />
</div>
</div>
}


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.idlineavuelo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.paisOrigen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.paisDestino)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.horapartida)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.horallegada)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cantescalas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.precio)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.idlineavuelo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.paisOrigen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.paisDestino)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.horapartida)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.horallegada)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cantescalas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.precio)
            </td>
        </tr>
    }

</table>